### PR TITLE
MPL-28 Fixed issue with stacktraces & other small fixes

### LINKED ISSUE #28: Display modules stacktrace & line of the issue
I found that right now MPL is not correctly filtering the stacktraces - so it's time to improve it.
Also it will be good to improve the example tests.

### PR DESCRIPTION
**Pull request by sparshev**
A couple of fixes to simplify debug & improve unit test example

fixes #28

### CODE REVIEW

**Comment by sparshev** [comment]
Possible displaying of lines will work only with not complicated module schema... For example 2 modules from different libs could have the same name and call of the overridden module will show the same line number for both modules...

Unfortunately it's quite unclear how to determine the proper file path instead of the available file name. Need additional testing.

**Comment by sparshev** [comment]
That's how MPL error will look like, when I added `asdasd` into the module logic.
new-stacktrace

**Comment by sparshev** [comment]
Hmmm, seems like the old logic is working correctly when the exception was threw from a pipeline step (`vars/*`)... Need to check the different locations of errors...

File: src/com/griddynamics/devops/mpl/Helper.groovy [hunk 1]
```diff
@@ -126,19 +126,51 @@ abstract class Helper {
...
+   *
    * @return  List with stack trace elements
    */
   static StackTraceElement[] getModuleStack(Throwable exception) {
     List stack = exception.getStackTrace()
+
+    // For jenkins to remove starting trace items
+    if( stack.last()?.getFileName() == 'Thread.java' ) {
+      // Finding the first MPLModule call and cutting the trace
+      for( def i = stack.size(); i--; i > 0 ) {
```
Comment (kvmenshikov) [inline src/com/griddynamics/devops/mpl/Helper.groovy]: It should be: for( def i = l.size(); i>0; i-- ) right?

File: src/com/griddynamics/devops/mpl/Helper.groovy [hunk 2]
```diff
@@ -126,19 +126,51 @@ abstract class Helper {
...
+        if( stack[i-1].getFileName()?.contains('MPLModule.groovy') )
```
Comment (kvmenshikov) [inline src/com/griddynamics/devops/mpl/Helper.groovy]: In the end of loop you will remove first frame if last (non-removed) is MPLModule.groovy.

File: src/com/griddynamics/devops/mpl/Helper.groovy [hunk 3]
```diff
@@ -126,19 +126,51 @@ abstract class Helper {
...
+      }
+    }
+
+    // Removing not interesting sources from the output to simplify debug
     for( def i = stack.size(); i--; i > 0 ) {
-      if( stack[i-1].getFileName()?.contains('vars/MPLModule.groovy') )
-        break
-      else
+      if( !stack[i]?.getFileName()?.endsWith('.groovy') ||
+          stack[i]?.getFileName() in ['MPLModule.groovy', 'Helper.groovy', 'PipelineTestHelper.groovy', 'MPLTestBase.groovy'] )
```
[the remark this answers is not in the document]
Comment (sparshev) [reply src/com/griddynamics/devops/mpl/Helper.groovy]: Those files are repeated alot, so I removed them. I think we can leave the last one (means source of the issue if it's happened in the listed excluded file).

File: src/com/griddynamics/devops/mpl/Helper.groovy (hunk 1 above)
Comment (sparshev) [reply src/com/griddynamics/devops/mpl/Helper.groovy]: Nope) Slightly different logic here.

File: src/com/griddynamics/devops/mpl/Helper.groovy (hunk 2 above)
Comment (sparshev) [reply src/com/griddynamics/devops/mpl/Helper.groovy]: So, the for(;;) logic is simple:
1. Execute first statement
2. Check bool(second statement) or exit
3. Execute third statement
4. Execute body
5. goto 2

```groovy
println "Forward"
for( def i=0; i<10; i++ )
  println i

println "Reverse"
for( def i=10; i>0; i-- )
  println i

println "Not typical forward"
for( def i=0; i++; )
  println i
println "Why not working: ${0 as Boolean}"

println "Not typical reverse"
for( def i=10; i--; )
  println i
```

Check the difference.

File: src/com/griddynamics/devops/mpl/Helper.groovy (hunk 1 above)
Comment (kvmenshikov) [reply src/com/griddynamics/devops/mpl/Helper.groovy]: Ok, got it. Can we remove third statement? Otherwise it looks like an error.

File: src/com/griddynamics/devops/mpl/Helper.groovy [hunk 4]
```diff
@@ -126,19 +126,51 @@ abstract class Helper {
...
     stack as StackTraceElement[]
   }
+
+  /**
+   * Looking the latest cause of the module file name and return it's line number
+   *
+   * @param module_path  MPL module path or module file name
+   * @param exception  container of the stacktrace
+   *
+   * @return  List with stack trace elements
```
Comment (kvmenshikov) [inline src/com/griddynamics/devops/mpl/Helper.groovy]: No, it return line number or null

Comment (sparshev) [reply src/com/griddynamics/devops/mpl/Helper.groovy]: Damn copypaste) Fixed.

**Comment by sparshev** [comment]
I added additional feature - to be able to use `env`, `props` & `currentConfig` in the `MPLPipelineConfig` closure body - no more weird defaults & functions inside the pipeline.

Also finally decided to leave the old logic of the stacktrace cutting - it's quite useful sometimes to determine what's actually wrong.

**Comment by sparshev** [comment]
Tested on jenkins pipeline - looks good.

File: vars/MPLPipelineConfig.groovy [hunk 5]
```diff
@@ -41,7 +43,14 @@ def call(body, Map defaults = [:], Map overrides = [:]) {
   if( body in Closure ) {
     body.resolveStrategy = Closure.DELEGATE_FIRST
     body.delegate = config
+
```
Comment (kvmenshikov) [inline vars/MPLPipelineConfig.groovy]: OMG, i understood how it works..
Let`s add following comments:
Line 50: # Main goal of execute body() here is update pipeline "defaults" which will be merged with override later. Delegation allow us do it.

File: vars/MPLPipelineConfig.groovy [hunk 6]
```diff
@@ -41,7 +43,14 @@ def call(body, Map defaults = [:], Map overrides = [:]) {
...
+    body.setProperty('env', env)
+    body.setProperty('params', params)
+    body.setProperty('currentBuild', currentBuild)
     body()
+    config.remove('env')
```
Comment (kvmenshikov) [inline vars/MPLPipelineConfig.groovy]: Maybe we can setProperty&remove for "config" variable? I suppose behavior will be same.
Otherwise it looks strange. If not, please add comment.
Due to our delegation strategy previous setProperty actually set property for "config" variable.

File: src/com/griddynamics/devops/mpl/Helper.groovy [hunk 7]
```diff
@@ -162,13 +155,20 @@ abstract class Helper {
    * @param module_path  MPL module path or module file name
    * @param exception  container of the stacktrace
    *
-   * @return  List with stack trace elements
+   * @return  Module line number or null if not found
    */
   static Integer getModuleExceptionLine(String module_path, Throwable exception) {
     List stack = exception.getStackTrace()
+    // First try to find the complete module path
```
[the remark this answers is not in the document]
Comment (sparshev) [reply src/com/griddynamics/devops/mpl/Helper.groovy]: Actually no - the logic will be changed. First try here to try to find the full path and will return if will find it. But your proposal will check both (full path and file name) for each line - it's completely different logic and we don't need it.

File: vars/MPLPipelineConfig.groovy (hunk 5 above)
Comment (sparshev) [reply vars/MPLPipelineConfig.groovy]: Added comments to clarify

File: vars/MPLPipelineConfig.groovy (hunk 6 above)
Comment (sparshev) [reply vars/MPLPipelineConfig.groovy]: Yep, changed to modify the config itself.
